components:

  docs/instrumentation:
    - nemoshlag


  instrumentation/opentelemetry-instrumentation-aio-pika:
    - ofek1weiss

  instrumentation/opentelemetry-instrumentation-boto3sqs:
    - oxeye-nikolay
    - nikosokolik
  
  instrumentation/opentelemetry-instrumentation-asyncclick:
    - jomcgi

  instrumentation/opentelemetry-instrumentation-kafka-python:
    - nozik
  
  instrumentation/opentelemetry-instrumentation-pika:
    - oxeye-nikolay
    - nikosokolik

  instrumentation/opentelemetry-instrumentation-redis:
    - sungwonh

  instrumentation/opentelemetry-instrumentation-remoulade:
    - ben-natan
    - machine424

  instrumentation/opentelemetry-instrumentation-confluent-kafka:
    - oxeye-dorkolog
    - dorkolog

  propagator/opentelemetry-propagator-aws-xray:
    - NathanielRN

  sdk-extension/opentelemetry-sdk-extension-aws:
    - NathanielRN
    - Kausik-A
    - srprash

  instrumentation/opentelemetry-instrumentation-tortoiseorm:
    - tonybaloney

  instrumentation/opentelemetry-instrumentation-tornado:
    - shalevr

  instrumentation/opentelemetry-instrumentation-urllib:
    - shalevr

  instrumentation/opentelemetry-instrumentation-urllib3:
    - shalevr

  instrumentation/opentelemetry-instrumentation-sqlalchemy:
    - shalevr

  instrumentation/opentelemetry-instrumentation-cassandra:
    - mattcontinisio

  instrumentation/opentelemetry-instrumentation-asyncio:
    - bourbonkk

  instrumentation/opentelemetry-instrumentation-psycopg:
    - federicobond

  instrumentation/opentelemetry-instrumentation-pymssql:
    - guillaumep

  instrumentation/opentelemetry-instrumentation-aiokafka:
    - dimastbk

  processor/opentelemetry-processor-baggage:
    - codeboten

  instrumentation-genai/:
    - karthikscale3
    - lmolkova
    - lzchen
    - gyliu513
    - nirga
    - alizenhom
    - codefromthecrypt
