components:

  docs/instrumentation:
    - nemoshlag

  instrumentation/opentelemetry-instrumentation-aio-pika:
    - ofek1weiss

  instrumentation/opentelemetry-instrumentation-boto3sqs:
    - oxeye-nikolay
    - nikosokolik
  
  instrumentation/opentelemetry-instrumentation-kafka-python:
    - nozik
  
  instrumentation/opentelemetry-instrumentation-pika:
    - oxeye-nikolay
    - nikosokolik

  instrumentation/opentelemetry-instrumentation-redis:
    - sungwonh

  instrumentation/opentelemetry-instrumentation-remoulade:
    - ben-natan
    - machine424

  instrumentation/opentelemetry-instrumentation-confluent-kafka:
    - oxeye-dorkolog
    - dorkolog

  propagator/opentelemetry-propagator-aws-xray:
    - NathanielRN

  sdk-extension/opentelemetry-sdk-extension-aws:
    - NathanielRN
    - Kausik-A

  instrumentation/opentelemetry-instrumentation-tortoiseorm:
    - tonybaloney

  instrumentation/opentelemetry-instrumentation-tornado:
    - shalevr

  instrumentation/opentelemetry-instrumentation-urllib:
    - shalevr
    - ocelotl

  instrumentation/opentelemetry-instrumentation-urllib3:
    - shalevr
    - ocelotl

  instrumentation/opentelemetry-instrumentation-sqlalchemy:
    - shalevr

  instrumentation/opentelemetry-instrumentation-flask:
    - ocelotl

  instrumentation/opentelemetry-instrumentation-jinja2:
    - ocelotl

  instrumentation/opentelemetry-instrumentation-logging:
    - ocelotl

  instrumentation/opentelemetry-instrumentation-requests:
    - ocelotl
