components:

  instrumentation/opentelemetry-instrumentation-aiokafka:
    - dimastbk

  instrumentation/opentelemetry-instrumentation-asyncclick:
    - jomcgi

  instrumentation/opentelemetry-instrumentation-asyncio:
    - bourbonkk

  instrumentation/opentelemetry-instrumentation-pymssql:
     - guillaumep

  instrumentation/opentelemetry-instrumentation-urllib:
    - shalevr

  instrumentation/opentelemetry-instrumentation-urllib3:
    - shalevr

  instrumentation-genai/:
    - karthikscale3
    - lmolkova
    - lzchen
    - gyliu513
    - nirga
    - alizenhom
    - codefromthecrypt

  processor/opentelemetry-processor-baggage:
    - codeboten

  propagator/opentelemetry-propagator-aws-xray:
    - jj22ee

  sdk-extension/opentelemetry-sdk-extension-aws:
    - srprash
    - jj22ee

  util/opentelemetry-util-genai:
    - DylanRussell
    - keith-decker

  instrumentation-genai/opentelemetry-instrumentation-langchain:
    - zhirafovod
    - wrisa