SHELL := /bin/bash
PIP_DIRS := $(shell find . -type f '(' -name "pyproject.toml" -o -name "*requirements.txt" ')' -not -path "./_template/*" -exec dirname {} \; | sort -u | egrep  '^./' )
DEPENDABOT_PATH=".github/dependabot.yml"

.PHONY: generate/dependabot
generate/dependabot:
	@echo "Recreating ${DEPENDABOT_PATH} file"
	@echo "# File generated by \"make generate/dependabot\"; DO NOT EDIT." > ${DEPENDABOT_PATH}
	@echo "version: 2" >> ${DEPENDABOT_PATH}
	@echo "updates:" >> ${DEPENDABOT_PATH}
	$(MAKE) dependabot/update DIR="/" PACKAGE="github-actions" LABEL="github_actions"
	$(MAKE) dependabot/update DIR="/" PACKAGE="pip" LABEL="python"
	@for dir in $(PIP_DIRS); do \
		$(MAKE) dependabot/update DIR=$${dir:1} PACKAGE="pip" LABEL="python"; \
	done

.PHONY: dependabot/update
dependabot/update:
	@echo "Add update rule for \"${PACKAGE}\" in \"${DIR}\"";
	@echo "  - directory: ${DIR}" >> ${DEPENDABOT_PATH};
	@echo "    package-ecosystem: ${PACKAGE}" >> ${DEPENDABOT_PATH};
	@echo "    labels:" >> ${DEPENDABOT_PATH};
	@echo "      - ${LABEL}" >> ${DEPENDABOT_PATH};
	@echo "      - dependencies" >> ${DEPENDABOT_PATH};
	@echo "      - Skip Changelog" >> ${DEPENDABOT_PATH};
	@echo "    schedule:" >> ${DEPENDABOT_PATH};
	@echo "      interval: weekly" >> ${DEPENDABOT_PATH};
	@echo "" >> ${DEPENDABOT_PATH};