[project]
name = "mcp-http-client-example"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.8.1",
    "opentelemetry-api>=1.37.0",
    "opentelemetry-distro>=0.58b0",
    "opentelemetry-exporter-otlp>=1.37.0",
    "opentelemetry-instrumentation-mcp",
    "opentelemetry-sdk",
    "pip>=25.2",
]
