"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright The OpenTelemetry Authors
SPDX-License-Identifier: Apache-2.0

Adapted from
https://github.com/jaegertracing/jaeger-idl/blob/ca9d21aa7c2f1cabe00f6ac844ca10def9053923/proto/api_v2/sampling.proto

The upstream file imports "gogoproto/gogo.proto" (Go-only marshaler/
unmarshaler/sizer extensions) and "google/api/annotations.proto" (REST/HTTP
transcoding for the RPC). Neither is meaningful for a pure-Python gRPC
client, so both imports and their associated options have been stripped
here. All messages, the enum, and the service/RPC are otherwise unchanged
from upstream. When bumping the pinned commit above, diff against the
upstream file and re-apply this same stripping.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _SamplingStrategyType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SamplingStrategyTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SamplingStrategyType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PROBABILISTIC: _SamplingStrategyType.ValueType  # 0
    RATE_LIMITING: _SamplingStrategyType.ValueType  # 1

class SamplingStrategyType(_SamplingStrategyType, metaclass=_SamplingStrategyTypeEnumTypeWrapper):
    """See description of the SamplingStrategyResponse.strategyType field."""

PROBABILISTIC: SamplingStrategyType.ValueType  # 0
RATE_LIMITING: SamplingStrategyType.ValueType  # 1
global___SamplingStrategyType = SamplingStrategyType

@typing_extensions.final
class ProbabilisticSamplingStrategy(google.protobuf.message.Message):
    """ProbabilisticSamplingStrategy samples traces with a fixed probability."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SAMPLINGRATE_FIELD_NUMBER: builtins.int
    samplingRate: builtins.float
    """samplingRate is the sampling probability in the range [0.0, 1.0]."""
    def __init__(
        self,
        *,
        samplingRate: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["samplingRate", b"samplingRate"]) -> None: ...

global___ProbabilisticSamplingStrategy = ProbabilisticSamplingStrategy

@typing_extensions.final
class RateLimitingSamplingStrategy(google.protobuf.message.Message):
    """RateLimitingSamplingStrategy samples a fixed number of traces per time interval.
    The typical implementations use the leaky bucket algorithm.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MAXTRACESPERSECOND_FIELD_NUMBER: builtins.int
    maxTracesPerSecond: builtins.int
    """TODO this field type should be changed to double, to support rates like 1 per minute."""
    def __init__(
        self,
        *,
        maxTracesPerSecond: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["maxTracesPerSecond", b"maxTracesPerSecond"]) -> None: ...

global___RateLimitingSamplingStrategy = RateLimitingSamplingStrategy

@typing_extensions.final
class OperationSamplingStrategy(google.protobuf.message.Message):
    """OperationSamplingStrategy is a sampling strategy for a given operation
    (aka endpoint, span name). Only probabilistic sampling is currently supported.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPERATION_FIELD_NUMBER: builtins.int
    PROBABILISTICSAMPLING_FIELD_NUMBER: builtins.int
    operation: builtins.str
    @property
    def probabilisticSampling(self) -> global___ProbabilisticSamplingStrategy: ...
    def __init__(
        self,
        *,
        operation: builtins.str = ...,
        probabilisticSampling: global___ProbabilisticSamplingStrategy | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["probabilisticSampling", b"probabilisticSampling"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["operation", b"operation", "probabilisticSampling", b"probabilisticSampling"]) -> None: ...

global___OperationSamplingStrategy = OperationSamplingStrategy

@typing_extensions.final
class PerOperationSamplingStrategies(google.protobuf.message.Message):
    """PerOperationSamplingStrategies is a combination of strategies for different endpoints
    as well as some service-wide defaults. It is particularly useful for services whose
    endpoints receive vastly different traffic, so that any single rate of sampling would
    result in either too much data for some endpoints or almost no data for other endpoints.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DEFAULTSAMPLINGPROBABILITY_FIELD_NUMBER: builtins.int
    DEFAULTLOWERBOUNDTRACESPERSECOND_FIELD_NUMBER: builtins.int
    PEROPERATIONSTRATEGIES_FIELD_NUMBER: builtins.int
    DEFAULTUPPERBOUNDTRACESPERSECOND_FIELD_NUMBER: builtins.int
    defaultSamplingProbability: builtins.float
    """defaultSamplingProbability is the sampling probability for spans that do not match
    any of the perOperationStrategies.
    """
    defaultLowerBoundTracesPerSecond: builtins.float
    """defaultLowerBoundTracesPerSecond defines a lower-bound rate limit used to ensure that
    there is some minimal amount of traces sampled for an endpoint that might otherwise
    be never sampled via probabilistic strategies. The limit is local to a service instance,
    so if a service is deployed with many (N) instances, the effective minimum rate of sampling
    will be N times higher. This setting applies to ALL operations, whether or not they match
    one of the perOperationStrategies.
    """
    @property
    def perOperationStrategies(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___OperationSamplingStrategy]:
        """perOperationStrategies describes sampling strategiesf for individual operations within
        a given service.
        """
    defaultUpperBoundTracesPerSecond: builtins.float
    """defaultUpperBoundTracesPerSecond defines an upper bound rate limit.
    However, almost no Jaeger SDKs support this parameter.
    """
    def __init__(
        self,
        *,
        defaultSamplingProbability: builtins.float = ...,
        defaultLowerBoundTracesPerSecond: builtins.float = ...,
        perOperationStrategies: collections.abc.Iterable[global___OperationSamplingStrategy] | None = ...,
        defaultUpperBoundTracesPerSecond: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["defaultLowerBoundTracesPerSecond", b"defaultLowerBoundTracesPerSecond", "defaultSamplingProbability", b"defaultSamplingProbability", "defaultUpperBoundTracesPerSecond", b"defaultUpperBoundTracesPerSecond", "perOperationStrategies", b"perOperationStrategies"]) -> None: ...

global___PerOperationSamplingStrategies = PerOperationSamplingStrategies

@typing_extensions.final
class SamplingStrategyResponse(google.protobuf.message.Message):
    """SamplingStrategyResponse contains an overall sampling strategy for a given service.
    This type should be treated as a union where only one of the strategy field is present.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STRATEGYTYPE_FIELD_NUMBER: builtins.int
    PROBABILISTICSAMPLING_FIELD_NUMBER: builtins.int
    RATELIMITINGSAMPLING_FIELD_NUMBER: builtins.int
    OPERATIONSAMPLING_FIELD_NUMBER: builtins.int
    strategyType: global___SamplingStrategyType.ValueType
    """Legacy field that was meant to indicate which one of the strategy fields
    below is present. This enum was not extended when per-operation strategy
    was introduced, because extending enum has backwards compatibility issues.
    The recommended approach for consumers is to ignore this field and instead
    checks the other fields being not null (starting with operationSampling).
    For producers, it is recommended to set this field correctly for probabilistic
    and rate-limiting strategies, but if per-operation strategy is returned,
    the enum can be set to 0 (probabilistic).
    """
    @property
    def probabilisticSampling(self) -> global___ProbabilisticSamplingStrategy: ...
    @property
    def rateLimitingSampling(self) -> global___RateLimitingSamplingStrategy: ...
    @property
    def operationSampling(self) -> global___PerOperationSamplingStrategies: ...
    def __init__(
        self,
        *,
        strategyType: global___SamplingStrategyType.ValueType = ...,
        probabilisticSampling: global___ProbabilisticSamplingStrategy | None = ...,
        rateLimitingSampling: global___RateLimitingSamplingStrategy | None = ...,
        operationSampling: global___PerOperationSamplingStrategies | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["operationSampling", b"operationSampling", "probabilisticSampling", b"probabilisticSampling", "rateLimitingSampling", b"rateLimitingSampling"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["operationSampling", b"operationSampling", "probabilisticSampling", b"probabilisticSampling", "rateLimitingSampling", b"rateLimitingSampling", "strategyType", b"strategyType"]) -> None: ...

global___SamplingStrategyResponse = SamplingStrategyResponse

@typing_extensions.final
class SamplingStrategyParameters(google.protobuf.message.Message):
    """SamplingStrategyParameters defines request parameters for remote sampler."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVICENAME_FIELD_NUMBER: builtins.int
    serviceName: builtins.str
    """serviceName is a required argument."""
    def __init__(
        self,
        *,
        serviceName: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["serviceName", b"serviceName"]) -> None: ...

global___SamplingStrategyParameters = SamplingStrategyParameters
