# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sampling_pb2 as sampling__pb2

GRPC_GENERATED_VERSION = '1.63.2'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sampling_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class SamplingManagerStub(object):
    """SamplingManager defines service for the remote sampler.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSamplingStrategy = channel.unary_unary(
                '/jaeger.api_v2.SamplingManager/GetSamplingStrategy',
                request_serializer=sampling__pb2.SamplingStrategyParameters.SerializeToString,
                response_deserializer=sampling__pb2.SamplingStrategyResponse.FromString,
                _registered_method=True)


class SamplingManagerServicer(object):
    """SamplingManager defines service for the remote sampler.
    """

    def GetSamplingStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SamplingManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSamplingStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSamplingStrategy,
                    request_deserializer=sampling__pb2.SamplingStrategyParameters.FromString,
                    response_serializer=sampling__pb2.SamplingStrategyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jaeger.api_v2.SamplingManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SamplingManager(object):
    """SamplingManager defines service for the remote sampler.
    """

    @staticmethod
    def GetSamplingStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jaeger.api_v2.SamplingManager/GetSamplingStrategy',
            sampling__pb2.SamplingStrategyParameters.SerializeToString,
            sampling__pb2.SamplingStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
