# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sampling.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esampling.proto\x12\rjaeger.api_v2\"5\n\x1dProbabilisticSamplingStrategy\x12\x14\n\x0csamplingRate\x18\x01 \x01(\x01\":\n\x1cRateLimitingSamplingStrategy\x12\x1a\n\x12maxTracesPerSecond\x18\x01 \x01(\x05\"{\n\x19OperationSamplingStrategy\x12\x11\n\toperation\x18\x01 \x01(\t\x12K\n\x15probabilisticSampling\x18\x02 \x01(\x0b\x32,.jaeger.api_v2.ProbabilisticSamplingStrategy\"\xe2\x01\n\x1ePerOperationSamplingStrategies\x12\"\n\x1a\x64\x65\x66\x61ultSamplingProbability\x18\x01 \x01(\x01\x12(\n defaultLowerBoundTracesPerSecond\x18\x02 \x01(\x01\x12H\n\x16perOperationStrategies\x18\x03 \x03(\x0b\x32(.jaeger.api_v2.OperationSamplingStrategy\x12(\n defaultUpperBoundTracesPerSecond\x18\x04 \x01(\x01\"\xb7\x02\n\x18SamplingStrategyResponse\x12\x39\n\x0cstrategyType\x18\x01 \x01(\x0e\x32#.jaeger.api_v2.SamplingStrategyType\x12K\n\x15probabilisticSampling\x18\x02 \x01(\x0b\x32,.jaeger.api_v2.ProbabilisticSamplingStrategy\x12I\n\x14rateLimitingSampling\x18\x03 \x01(\x0b\x32+.jaeger.api_v2.RateLimitingSamplingStrategy\x12H\n\x11operationSampling\x18\x04 \x01(\x0b\x32-.jaeger.api_v2.PerOperationSamplingStrategies\"1\n\x1aSamplingStrategyParameters\x12\x13\n\x0bserviceName\x18\x01 \x01(\t*<\n\x14SamplingStrategyType\x12\x11\n\rPROBABILISTIC\x10\x00\x12\x11\n\rRATE_LIMITING\x10\x01\x32~\n\x0fSamplingManager\x12k\n\x13GetSamplingStrategy\x12).jaeger.api_v2.SamplingStrategyParameters\x1a\'.jaeger.api_v2.SamplingStrategyResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sampling_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAMPLINGSTRATEGYTYPE']._serialized_start=867
  _globals['_SAMPLINGSTRATEGYTYPE']._serialized_end=927
  _globals['_PROBABILISTICSAMPLINGSTRATEGY']._serialized_start=33
  _globals['_PROBABILISTICSAMPLINGSTRATEGY']._serialized_end=86
  _globals['_RATELIMITINGSAMPLINGSTRATEGY']._serialized_start=88
  _globals['_RATELIMITINGSAMPLINGSTRATEGY']._serialized_end=146
  _globals['_OPERATIONSAMPLINGSTRATEGY']._serialized_start=148
  _globals['_OPERATIONSAMPLINGSTRATEGY']._serialized_end=271
  _globals['_PEROPERATIONSAMPLINGSTRATEGIES']._serialized_start=274
  _globals['_PEROPERATIONSAMPLINGSTRATEGIES']._serialized_end=500
  _globals['_SAMPLINGSTRATEGYRESPONSE']._serialized_start=503
  _globals['_SAMPLINGSTRATEGYRESPONSE']._serialized_end=814
  _globals['_SAMPLINGSTRATEGYPARAMETERS']._serialized_start=816
  _globals['_SAMPLINGSTRATEGYPARAMETERS']._serialized_end=865
  _globals['_SAMPLINGMANAGER']._serialized_start=929
  _globals['_SAMPLINGMANAGER']._serialized_end=1055
# @@protoc_insertion_point(module_scope)
