[project]
name = "mcp-server-foo"
version = "0.1.0"
description = "A simple MCP server exposing a tool"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "OpenTelemetry" }]
maintainers = [
]
keywords = ["mcp", "server", "web", "fetch"]
license = { text = "MIT" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
]
dependencies = [
    "anyio>=4.5",
    "boto3>=1.40.52",
    "click>=8.2.0",
    "httpx>=0.27",
    "mcp[cli]>=1.17.0",
    "requests>=2.32.5",
]

[project.scripts]
mcp-server-foo = "mcp_simple_tool.server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["mcp_simple_tool"]

[tool.pyright]
include = ["mcp_simple_tool"]
venvPath = "."
venv = ".venv"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.uv]
dev-dependencies = ["pyright>=1.1.378", "pytest>=8.3.3", "ruff>=0.6.9"]
