apiVersion: apps/v1
kind: Deployment
metadata:
  name: langgraph-multi-agent-utils
  namespace: demo-app
  labels:
    app: langgraph-multi-agent-utils
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langgraph-multi-agent-utils
  template:
    metadata:
      labels:
        app: langgraph-multi-agent-utils
    spec:
      containers:
      - name: multi-agent-rag
        image: pranair2800/langgraph-multi-agent-utils:1.0
        ports:
        - containerPort: 8000
        env:
        - name: OTEL_SERVICE_NAME
          value: "langgraph-multi-agent-utils"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "deployment.environment=o11y-inframon-ai"
        - name: SPLUNK_OTEL_AGENT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(SPLUNK_OTEL_AGENT):4317"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_PYTHON_EXCLUDED_URLS
          value: "^(https?://)?[^/]+(/)?$"
        - name: OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT
          value: "true"
        - name: OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT_MODE
          value: "SPAN_AND_EVENT"
        - name: OTEL_INSTRUMENTATION_GENAI_EMITTERS
          value: "span_metric_event"
        - name: OTEL_SEMCONV_STABILITY_OPT_IN
          value: "gen_ai_latest_experimental"
        - name: OTEL_LOGS_EXPORTER
          value: "otlp"
        - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
          value: "true"
        - name: OTEL_INSTRUMENTATION_LANGCHAIN_CAPTURE_MESSAGE_CONTENT
          value: "true"
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: "DELTA"
        - name: SPLUNK_PROFILER_ENABLED
          value: "true"
        - name: CISCO_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: cisco-credentials
              key: client-id
        - name: CISCO_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: cisco-credentials
              key: client-secret
        - name: CISCO_APP_KEY
          valueFrom:
            secretKeyRef:
              name: cisco-credentials
              key: app-key
        - name: TAVILY_API_KEY
          valueFrom:
            secretKeyRef:
              name: cisco-credentials
              key: tavily-api-key
        - name: WEAVIATE_HOST
          value: "weaviate-rag.demo-app.svc.cluster.local"
        - name: WEAVIATE_PORT
          value: "8080"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
---
apiVersion: v1
kind: Service
metadata:
  name: langgraph-multi-agent-utils-service
  namespace: demo-app
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: langgraph-multi-agent-utils
