# Generated from anyvalue.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.3.0 with parameter "init_files=false".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc

if TYPE_CHECKING:
    from protobuf import DescFile, Oneof


_AnyValueFields: TypeAlias = Literal["string_value", "bool_value", "int_value", "double_value", "array_value", "kvlist_value", "bytes_value"]

class AnyValue(Message[_AnyValueFields]):
    """
    AnyValue is used to represent any type of attribute value. AnyValue may contain a
    primitive value such as a string or integer or it may contain an arbitrary nested
    object containing arrays, key-value lists and primitives.

    ```proto
    message opamp.proto.AnyValue
    ```

    Attributes:
        value:
            The value is one of the listed fields. It is valid for all values to be unspecified
            in which case this AnyValue is considered to be "null".

            ```proto
            oneof value
            ```
    """

    __slots__ = ("value",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            value: Oneof[Literal["string_value"], str] | Oneof[Literal["bool_value"], bool] | Oneof[Literal["int_value"], int] | Oneof[Literal["double_value"], float] | Oneof[Literal["array_value"], ArrayValue] | Oneof[Literal["kvlist_value"], KeyValueList] | Oneof[Literal["bytes_value"], bytes] | None = None,
        ) -> None:
            pass

        value: Oneof[Literal["string_value"], str] | Oneof[Literal["bool_value"], bool] | Oneof[Literal["int_value"], int] | Oneof[Literal["double_value"], float] | Oneof[Literal["array_value"], ArrayValue] | Oneof[Literal["kvlist_value"], KeyValueList] | Oneof[Literal["bytes_value"], bytes] | None

_ArrayValueFields: TypeAlias = Literal["values"]

class ArrayValue(Message[_ArrayValueFields]):
    """
    ArrayValue is a list of AnyValue messages. We need ArrayValue as a message
    since oneof in AnyValue does not allow repeated fields.

    ```proto
    message opamp.proto.ArrayValue
    ```

    Attributes:
        values:
            Array of values. The array may be empty (contain 0 elements).

            ```proto
            repeated opamp.proto.AnyValue values = 1;
            ```
    """

    __slots__ = ("values",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            values: list[AnyValue] | None = None,
        ) -> None:
            pass

        values: list[AnyValue]

_KeyValueListFields: TypeAlias = Literal["values"]

class KeyValueList(Message[_KeyValueListFields]):
    """
    KeyValueList is a list of KeyValue messages. We need KeyValueList as a message
    since `oneof` in AnyValue does not allow repeated fields. Everywhere else where we need
    a list of KeyValue messages (e.g. in Span) we use `repeated KeyValue` directly to
    avoid unnecessary extra wrapping (which slows down the protocol). The 2 approaches
    are semantically equivalent.

    ```proto
    message opamp.proto.KeyValueList
    ```

    Attributes:
        values:
            A collection of key/value pairs of key-value pairs. The list may be empty (may
            contain 0 elements).

            ```proto
            repeated opamp.proto.KeyValue values = 1;
            ```
    """

    __slots__ = ("values",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            values: list[KeyValue] | None = None,
        ) -> None:
            pass

        values: list[KeyValue]

_KeyValueFields: TypeAlias = Literal["key", "value"]

class KeyValue(Message[_KeyValueFields]):
    """
    KeyValue is a key-value pair that is used to store Span attributes, Link
    attributes, etc.

    ```proto
    message opamp.proto.KeyValue
    ```

    Attributes:
        key:
            ```proto
            string key = 1;
            ```
        value:
            ```proto
            optional opamp.proto.AnyValue value = 2;
            ```
    """

    __slots__ = ("key", "value")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            key: str = "",
            value: AnyValue | None = None,
        ) -> None:
            pass

        key: str
        value: AnyValue | None


_DESC = file_desc(
    b'\n\x0eanyvalue.proto\x12\x0bopamp.proto"\xbc\x02\n\x08AnyValue\x12#\n\x0cstring_value\x18\x01 \x01(\tH\x00R\x0bstringValue\x12\x1f\n\nbool_value\x18\x02 \x01(\x08H\x00R\tboolValue\x12\x1d\n\tint_value\x18\x03 \x01(\x03H\x00R\x08intValue\x12#\n\x0cdouble_value\x18\x04 \x01(\x01H\x00R\x0bdoubleValue\x12:\n\x0barray_value\x18\x05 \x01(\x0b2\x17.opamp.proto.ArrayValueH\x00R\narrayValue\x12>\n\x0ckvlist_value\x18\x06 \x01(\x0b2\x19.opamp.proto.KeyValueListH\x00R\x0bkvlistValue\x12!\n\x0bbytes_value\x18\x07 \x01(\x0cH\x00R\nbytesValueB\x07\n\x05value";\n\nArrayValue\x12-\n\x06values\x18\x01 \x03(\x0b2\x15.opamp.proto.AnyValueR\x06values"=\n\x0cKeyValueList\x12-\n\x06values\x18\x01 \x03(\x0b2\x15.opamp.proto.KeyValueR\x06values"I\n\x08KeyValue\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12+\n\x05value\x18\x02 \x01(\x0b2\x15.opamp.proto.AnyValueR\x05valueB.Z,github.com/open-telemetry/opamp-go/protobufsb\x06proto3',
    [],
    {
        "AnyValue": AnyValue,
        "ArrayValue": ArrayValue,
        "KeyValueList": KeyValueList,
        "KeyValue": KeyValue,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `anyvalue.proto`."""
    return _DESC
